// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TasteTheWorld.Data;

#nullable disable

namespace TasteTheWorld.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TasteTheWorld.Models.BucketList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTried")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId");

                    b.ToTable("BucketLists");
                });

            modelBuilder.Entity("TasteTheWorld.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BgColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryFlag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BgColor = "#1a3a5c",
                            Country = "Turkey",
                            CountryFlag = "🇹🇷",
                            Emoji = "🕌",
                            ImageUrl = "/images/cities/istanbul.jpg",
                            Name = "Istanbul"
                        },
                        new
                        {
                            Id = 2,
                            BgColor = "#1a1a2e",
                            Country = "Japan",
                            CountryFlag = "🇯🇵",
                            Emoji = "⛩️",
                            ImageUrl = "/images/cities/tokyo.jpg",
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 3,
                            BgColor = "#006994",
                            Country = "Italy",
                            CountryFlag = "🇮🇹",
                            Emoji = "🏛️",
                            ImageUrl = "/images/cities/napoli.jpg",
                            Name = "Naples"
                        },
                        new
                        {
                            Id = 4,
                            BgColor = "#1a4a2e",
                            Country = "Thailand",
                            CountryFlag = "🇹🇭",
                            Emoji = "🛺",
                            ImageUrl = "/images/cities/bangkok.jpg",
                            Name = "Bangkok"
                        },
                        new
                        {
                            Id = 5,
                            BgColor = "#3a1a0a",
                            Country = "Mexico",
                            CountryFlag = "🇲🇽",
                            Emoji = "🌵",
                            ImageUrl = "/images/cities/mexico-city.jpg",
                            Name = "Mexico City"
                        },
                        new
                        {
                            Id = 6,
                            BgColor = "#1a1a4a",
                            Country = "France",
                            CountryFlag = "🇫🇷",
                            Emoji = "🗼",
                            ImageUrl = "/images/cities/paris.jpg",
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 7,
                            BgColor = "#8B0000",
                            Country = "Spain",
                            CountryFlag = "🇪🇸",
                            Emoji = "🐂",
                            ImageUrl = "/images/cities/madrid.jpg",
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = 8,
                            BgColor = "#c0392b",
                            Country = "Spain",
                            CountryFlag = "🇪🇸",
                            Emoji = "🏖️",
                            ImageUrl = "/images/cities/barcelona.jpg",
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 9,
                            BgColor = "#2c3e50",
                            Country = "USA",
                            CountryFlag = "🇺🇸",
                            Emoji = "🗽",
                            ImageUrl = "/images/cities/new-york.jpg",
                            Name = "New York"
                        },
                        new
                        {
                            Id = 10,
                            BgColor = "#b5770d",
                            Country = "UAE",
                            CountryFlag = "🇦🇪",
                            Emoji = "🏙️",
                            ImageUrl = "/images/cities/dubai.jpg",
                            Name = "Dubai"
                        },
                        new
                        {
                            Id = 11,
                            BgColor = "#c0392b",
                            Country = "Singapore",
                            CountryFlag = "🇸🇬",
                            Emoji = "🦁",
                            ImageUrl = "/images/cities/singapore.jpg",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 12,
                            BgColor = "#2d3436",
                            Country = "Germany",
                            CountryFlag = "🇩🇪",
                            Emoji = "🐻",
                            ImageUrl = "/images/cities/berlin.jpg",
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 13,
                            BgColor = "#6c3483",
                            Country = "India",
                            CountryFlag = "🇮🇳",
                            Emoji = "🕍",
                            ImageUrl = "/images/cities/mumbai.jpg",
                            Name = "Mumbai"
                        },
                        new
                        {
                            Id = 14,
                            BgColor = "#1e8449",
                            Country = "Peru",
                            CountryFlag = "🇵🇪",
                            Emoji = "🦙",
                            ImageUrl = "/images/cities/lima.jpg",
                            Name = "Lima"
                        },
                        new
                        {
                            Id = 15,
                            BgColor = "#784212",
                            Country = "Morocco",
                            CountryFlag = "🇲🇦",
                            Emoji = "🏜️",
                            ImageUrl = "/images/cities/marakes.jpg",
                            Name = "Marrakech"
                        });
                });

            modelBuilder.Entity("TasteTheWorld.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSpicy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Street Food",
                            CityId = 1,
                            Description = "Istanbul's legendary street food. Fresh grilled fish served with salad and lemon at the Galata Bridge.",
                            Emoji = "🥙",
                            ImageUrl = "/images/foods/balik-ekmek.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Balik Ekmek",
                            PriceRange = "₺",
                            Rating = 4.5999999999999996,
                            ReviewCount = 512
                        },
                        new
                        {
                            Id = 2,
                            Category = "Dessert",
                            CityId = 1,
                            Description = "A legendary dessert from Antep. Thin kadaif pastry filled with fresh cheese and soaked in sweet syrup, served hot.",
                            Emoji = "🍮",
                            ImageUrl = "/images/foods/kunefe.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Kunefe",
                            PriceRange = "₺₺",
                            Rating = 4.7000000000000002,
                            ReviewCount = 452
                        },
                        new
                        {
                            Id = 3,
                            Category = "Meat Dish",
                            CityId = 1,
                            Description = "The famous kebab of Bursa. Döner meat served with melted butter, tomato sauce, and yogurt.",
                            Emoji = "🥗",
                            ImageUrl = "/images/foods/iskender.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Iskender Kebab",
                            PriceRange = "₺₺",
                            Rating = 4.7999999999999998,
                            ReviewCount = 634
                        },
                        new
                        {
                            Id = 4,
                            Category = "Street Food",
                            CityId = 1,
                            Description = "An Istanbul street staple. Mussels stuffed with spiced rice, squeezed with lemon before eating.",
                            Emoji = "🦪",
                            ImageUrl = "/images/foods/midye.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Stuffed Mussels",
                            PriceRange = "₺",
                            Rating = 4.4000000000000004,
                            ReviewCount = 389
                        },
                        new
                        {
                            Id = 5,
                            Category = "Street Food",
                            CityId = 1,
                            Description = "The iconic Turkish bagel. Crispy, sesame-coated ring-shaped bread fresh from the oven.",
                            Emoji = "🥯",
                            ImageUrl = "/images/foods/simit.jpg",
                            IsSpicy = false,
                            IsVegetarian = true,
                            Name = "Simit",
                            PriceRange = "₺",
                            Rating = 4.5,
                            ReviewCount = 720
                        },
                        new
                        {
                            Id = 6,
                            Category = "Soup",
                            CityId = 2,
                            Description = "The soul of Tokyo. Rich pork bone broth simmered for hours, served with thin noodles, egg, and char siu.",
                            Emoji = "🍜",
                            ImageUrl = "/images/foods/ramen.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Tonkotsu Ramen",
                            PriceRange = "€€€",
                            Rating = 4.7000000000000002,
                            ReviewCount = 781
                        },
                        new
                        {
                            Id = 7,
                            Category = "Seafood",
                            CityId = 2,
                            Description = "A chef's selection of fresh fish and rice combinations. Tokyo's most prestigious dining experience.",
                            Emoji = "🍣",
                            ImageUrl = "/images/foods/sushi.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Sushi Omakase",
                            PriceRange = "€€€€",
                            Rating = 4.9000000000000004,
                            ReviewCount = 345
                        },
                        new
                        {
                            Id = 8,
                            Category = "Grilled",
                            CityId = 2,
                            Description = "Charcoal-grilled chicken skewers. Served with tare sauce or salt, pairs perfectly with a cold beer.",
                            Emoji = "🍢",
                            ImageUrl = "/images/foods/yakitori.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Yakitori",
                            PriceRange = "€€",
                            Rating = 4.5,
                            ReviewCount = 456
                        },
                        new
                        {
                            Id = 9,
                            Category = "Street Food",
                            CityId = 2,
                            Description = "Small balls filled with octopus pieces. Served with okonomiyaki sauce, mayo, and bonito flakes.",
                            Emoji = "🐙",
                            ImageUrl = "/images/foods/takoyaki.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Takoyaki",
                            PriceRange = "€",
                            Rating = 4.5999999999999996,
                            ReviewCount = 523
                        },
                        new
                        {
                            Id = 10,
                            Category = "Pizza",
                            CityId = 3,
                            Description = "The original Neapolitan pizza. Baked in a wood-fired oven in 90 seconds, with San Marzano tomatoes and buffalo mozzarella.",
                            Emoji = "🍕",
                            ImageUrl = "/images/foods/pizza.jpg",
                            IsSpicy = false,
                            IsVegetarian = true,
                            Name = "Pizza Napoletana",
                            PriceRange = "€€",
                            Rating = 4.7999999999999998,
                            ReviewCount = 943
                        },
                        new
                        {
                            Id = 11,
                            Category = "Bakery",
                            CityId = 3,
                            Description = "Naples' iconic shell-shaped pastry. Crispy dough filled with ricotta and orange zest.",
                            Emoji = "🥐",
                            ImageUrl = "/images/foods/sfogliatella.jpg",
                            IsSpicy = false,
                            IsVegetarian = true,
                            Name = "Sfogliatella",
                            PriceRange = "€",
                            Rating = 4.5999999999999996,
                            ReviewCount = 312
                        },
                        new
                        {
                            Id = 12,
                            Category = "Pasta",
                            CityId = 3,
                            Description = "Naples' seafood pasta made with fresh clams, garlic, white wine, and parsley.",
                            Emoji = "🍝",
                            ImageUrl = "/images/foods/vongole.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Spaghetti alle Vongole",
                            PriceRange = "€€€",
                            Rating = 4.7000000000000002,
                            ReviewCount = 428
                        },
                        new
                        {
                            Id = 13,
                            Category = "Noodles",
                            CityId = 4,
                            Description = "Thailand's national dish. Rice noodles stir-fried with shrimp, egg, peanuts, and tamarind sauce.",
                            Emoji = "🍝",
                            ImageUrl = "/images/foods/pad-thai.jpg",
                            IsSpicy = true,
                            IsVegetarian = false,
                            Name = "Pad Thai",
                            PriceRange = "€€",
                            Rating = 4.5999999999999996,
                            ReviewCount = 385
                        },
                        new
                        {
                            Id = 14,
                            Category = "Soup",
                            CityId = 4,
                            Description = "Thailand's sour and spicy soup. Made with shrimp, lemongrass, galangal, kaffir lime leaves, and chili.",
                            Emoji = "🍲",
                            ImageUrl = "/images/foods/tom-yum.jpg",
                            IsSpicy = true,
                            IsVegetarian = false,
                            Name = "Tom Yum Soup",
                            PriceRange = "€€",
                            Rating = 4.7000000000000002,
                            ReviewCount = 467
                        },
                        new
                        {
                            Id = 15,
                            Category = "Dessert",
                            CityId = 4,
                            Description = "Thailand's most beloved dessert. Sweet sticky rice topped with fresh mango slices and coconut milk.",
                            Emoji = "🥭",
                            ImageUrl = "/images/foods/mango-rice.jpg",
                            IsSpicy = false,
                            IsVegetarian = true,
                            Name = "Mango Sticky Rice",
                            PriceRange = "€",
                            Rating = 4.7999999999999998,
                            ReviewCount = 534
                        },
                        new
                        {
                            Id = 16,
                            Category = "Street Food",
                            CityId = 5,
                            Description = "Mexico City's most iconic street food. Marinated pork cooked on a vertical spit, served with pineapple and cilantro.",
                            Emoji = "🌮",
                            ImageUrl = "/images/foods/tacos.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Tacos al Pastor",
                            PriceRange = "€",
                            Rating = 4.5,
                            ReviewCount = 623
                        },
                        new
                        {
                            Id = 17,
                            Category = "Appetizer",
                            CityId = 5,
                            Description = "Mexico's essential sauce made with fresh avocado, tomato, onion, cilantro, and lime.",
                            Emoji = "🥑",
                            ImageUrl = "/images/foods/guacamole.jpg",
                            IsSpicy = false,
                            IsVegetarian = true,
                            Name = "Guacamole",
                            PriceRange = "€",
                            Rating = 4.5999999999999996,
                            ReviewCount = 412
                        },
                        new
                        {
                            Id = 18,
                            Category = "Meat Dish",
                            CityId = 5,
                            Description = "Mexico's national dish. Stuffed peppers served with walnut sauce and pomegranate seeds — a colorful feast.",
                            Emoji = "🫑",
                            ImageUrl = "/images/foods/chiles.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Chiles en Nogada",
                            PriceRange = "€€€",
                            Rating = 4.7000000000000002,
                            ReviewCount = 289
                        },
                        new
                        {
                            Id = 19,
                            Category = "Bakery",
                            CityId = 6,
                            Description = "Paris' morning ritual. A classic French pastry made with buttery, flaky, golden-layered dough.",
                            Emoji = "🥐",
                            ImageUrl = "/images/foods/croissant.jpg",
                            IsSpicy = false,
                            IsVegetarian = true,
                            Name = "Croissant",
                            PriceRange = "€",
                            Rating = 4.7000000000000002,
                            ReviewCount = 892
                        },
                        new
                        {
                            Id = 20,
                            Category = "Meat Dish",
                            CityId = 6,
                            Description = "The crown of French cuisine. Beef slow-cooked in Burgundy wine with mushrooms and root vegetables.",
                            Emoji = "🥩",
                            ImageUrl = "/images/foods/boeuf.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Boeuf Bourguignon",
                            PriceRange = "€€€€",
                            Rating = 4.7999999999999998,
                            ReviewCount = 334
                        },
                        new
                        {
                            Id = 21,
                            Category = "Dessert",
                            CityId = 6,
                            Description = "An icon of French cuisine. Velvety vanilla custard topped with a caramelized sugar crust.",
                            Emoji = "🍮",
                            ImageUrl = "/images/foods/creme-brulee.jpg",
                            IsSpicy = false,
                            IsVegetarian = true,
                            Name = "Crème Brûlée",
                            PriceRange = "€€",
                            Rating = 4.7999999999999998,
                            ReviewCount = 567
                        },
                        new
                        {
                            Id = 22,
                            Category = "Rice Dish",
                            CityId = 7,
                            Description = "Spain's national dish from Valencia. A colorful feast of saffron, seafood, and rice.",
                            Emoji = "🥘",
                            ImageUrl = "/images/foods/paella.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Paella",
                            PriceRange = "€€€",
                            Rating = 4.7000000000000002,
                            ReviewCount = 612
                        },
                        new
                        {
                            Id = 23,
                            Category = "Charcuterie",
                            CityId = 7,
                            Description = "Spain's pride. Premium ham from acorn-fed black pigs, aged for years to perfection.",
                            Emoji = "🥓",
                            ImageUrl = "/images/foods/jamon.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Jamón Ibérico",
                            PriceRange = "€€€€",
                            Rating = 4.9000000000000004,
                            ReviewCount = 445
                        },
                        new
                        {
                            Id = 24,
                            Category = "Dessert",
                            CityId = 7,
                            Description = "Madrid's morning treat. Fried dough sticks served with thick hot chocolate.",
                            Emoji = "🍩",
                            ImageUrl = "/images/foods/churros.jpg",
                            IsSpicy = false,
                            IsVegetarian = true,
                            Name = "Churros con Chocolate",
                            PriceRange = "€",
                            Rating = 4.5999999999999996,
                            ReviewCount = 723
                        },
                        new
                        {
                            Id = 25,
                            Category = "Appetizer",
                            CityId = 8,
                            Description = "Catalonia's simplest and most delicious dish. Bread rubbed with tomato, garlic, and olive oil — simplicity at its finest.",
                            Emoji = "🍅",
                            ImageUrl = "/images/foods/pan-tomate.jpg",
                            IsSpicy = false,
                            IsVegetarian = true,
                            Name = "Pan con Tomate",
                            PriceRange = "€",
                            Rating = 4.5,
                            ReviewCount = 398
                        },
                        new
                        {
                            Id = 26,
                            Category = "Dessert",
                            CityId = 8,
                            Description = "The ancestor of crème brûlée. Catalan custard flavored with cinnamon and lemon zest.",
                            Emoji = "🍮",
                            ImageUrl = "/images/foods/crema-catalana.jpg",
                            IsSpicy = false,
                            IsVegetarian = true,
                            Name = "Crema Catalana",
                            PriceRange = "€€",
                            Rating = 4.7000000000000002,
                            ReviewCount = 312
                        },
                        new
                        {
                            Id = 27,
                            Category = "Pizza",
                            CityId = 9,
                            Description = "New York's iconic large pizza slice. Thin crust, rich sauce, mozzarella — folding it is mandatory!",
                            Emoji = "🍕",
                            ImageUrl = "/images/foods/ny-pizza.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "NY Pizza Slice",
                            PriceRange = "€",
                            Rating = 4.5999999999999996,
                            ReviewCount = 1205
                        },
                        new
                        {
                            Id = 28,
                            Category = "Dessert",
                            CityId = 9,
                            Description = "New York-style cheesecake. A legendary dessert made with cream cheese, eggs, and sugar on a graham cracker crust.",
                            Emoji = "🎂",
                            ImageUrl = "/images/foods/cheesecake.jpg",
                            IsSpicy = false,
                            IsVegetarian = true,
                            Name = "Cheesecake",
                            PriceRange = "€€",
                            Rating = 4.7999999999999998,
                            ReviewCount = 876
                        },
                        new
                        {
                            Id = 29,
                            Category = "Breakfast",
                            CityId = 9,
                            Description = "A New York icon. Sesame bagel loaded with cream cheese, smoked salmon, capers, and onion.",
                            Emoji = "🥯",
                            ImageUrl = "/images/foods/bagel.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Bagel with Lox",
                            PriceRange = "€€",
                            Rating = 4.7000000000000002,
                            ReviewCount = 534
                        },
                        new
                        {
                            Id = 30,
                            Category = "Meat Dish",
                            CityId = 10,
                            Description = "Dubai's traditional dish. Wheat and meat slow-cooked and mashed together — a Ramadan staple.",
                            Emoji = "🍲",
                            ImageUrl = "/images/foods/harees.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Al Harees",
                            PriceRange = "€€",
                            Rating = 4.5,
                            ReviewCount = 234
                        },
                        new
                        {
                            Id = 31,
                            Category = "Street Food",
                            CityId = 10,
                            Description = "The Middle Eastern flavor found on every corner of Dubai. Spiced meat with hummus, pickles, and hot sauce in flatbread.",
                            Emoji = "🌯",
                            ImageUrl = "/images/foods/shawarma.jpg",
                            IsSpicy = true,
                            IsVegetarian = false,
                            Name = "Shawarma",
                            PriceRange = "€",
                            Rating = 4.5999999999999996,
                            ReviewCount = 892
                        },
                        new
                        {
                            Id = 32,
                            Category = "Chicken",
                            CityId = 11,
                            Description = "Singapore's national dish. Tender poached chicken served with aromatic rice, ginger sauce, and chili.",
                            Emoji = "🍚",
                            ImageUrl = "/images/foods/chicken-rice.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Hainanese Chicken Rice",
                            PriceRange = "€",
                            Rating = 4.7999999999999998,
                            ReviewCount = 678
                        },
                        new
                        {
                            Id = 33,
                            Category = "Seafood",
                            CityId = 11,
                            Description = "Singapore's pride. Massive crab cooked in a tomato-chili sauce, served with mantou bread.",
                            Emoji = "🦀",
                            ImageUrl = "/images/foods/chilli-crab.jpg",
                            IsSpicy = true,
                            IsVegetarian = false,
                            Name = "Chilli Crab",
                            PriceRange = "€€€€",
                            Rating = 4.9000000000000004,
                            ReviewCount = 445
                        },
                        new
                        {
                            Id = 34,
                            Category = "Street Food",
                            CityId = 12,
                            Description = "Berlin's symbol. Grilled or fried sausage served with curry sauce and curry powder — an iconic street food.",
                            Emoji = "🌭",
                            ImageUrl = "/images/foods/currywurst.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Currywurst",
                            PriceRange = "€",
                            Rating = 4.5,
                            ReviewCount = 789
                        },
                        new
                        {
                            Id = 35,
                            Category = "Street Food",
                            CityId = 12,
                            Description = "Berlin's heritage from Turkish immigrants. Lavash bread filled with fresh vegetables, yogurt, and spiced meat.",
                            Emoji = "🥙",
                            ImageUrl = "/images/foods/berliner-doner.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Berliner Döner",
                            PriceRange = "€",
                            Rating = 4.7000000000000002,
                            ReviewCount = 934
                        },
                        new
                        {
                            Id = 36,
                            Category = "Chicken",
                            CityId = 13,
                            Description = "India's world-famous dish. Tender chicken floating in a creamy tomato-butter sauce. Perfect with naan bread.",
                            Emoji = "🍛",
                            ImageUrl = "/images/foods/butter-chicken.jpg",
                            IsSpicy = true,
                            IsVegetarian = false,
                            Name = "Butter Chicken",
                            PriceRange = "€€",
                            Rating = 4.7999999999999998,
                            ReviewCount = 823
                        },
                        new
                        {
                            Id = 37,
                            Category = "Street Food",
                            CityId = 13,
                            Description = "Mumbai's burger. A spiced potato fritter in a pav bun, served with chutney — the city's favorite street snack.",
                            Emoji = "🍔",
                            ImageUrl = "/images/foods/vada-pav.jpg",
                            IsSpicy = true,
                            IsVegetarian = true,
                            Name = "Vada Pav",
                            PriceRange = "₺",
                            Rating = 4.5999999999999996,
                            ReviewCount = 567
                        },
                        new
                        {
                            Id = 38,
                            Category = "Seafood",
                            CityId = 14,
                            Description = "Peru's pride. Fresh seafood marinated in lime juice, ají amarillo, and red onion — the world's most refreshing dish.",
                            Emoji = "🐟",
                            ImageUrl = "/images/foods/ceviche.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Ceviche",
                            PriceRange = "€€€",
                            Rating = 4.9000000000000004,
                            ReviewCount = 567
                        },
                        new
                        {
                            Id = 39,
                            Category = "Meat Dish",
                            CityId = 14,
                            Description = "A Peruvian-Chinese fusion. Beef stir-fried with tomatoes, garlic, soy sauce, and french fries.",
                            Emoji = "🥩",
                            ImageUrl = "/images/foods/lomo-saltado.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Lomo Saltado",
                            PriceRange = "€€€",
                            Rating = 4.7000000000000002,
                            ReviewCount = 389
                        },
                        new
                        {
                            Id = 40,
                            Category = "Meat Dish",
                            CityId = 15,
                            Description = "Morocco's symbol. Lamb slow-cooked with spices and dried fruits in a conical clay pot.",
                            Emoji = "🫕",
                            ImageUrl = "/images/foods/tagine.jpg",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Name = "Tagine",
                            PriceRange = "€€",
                            Rating = 4.7999999999999998,
                            ReviewCount = 478
                        });
                });

            modelBuilder.Entity("TasteTheWorld.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Ahmet Y.",
                            Comment = "A must-eat in Istanbul! Having it at the Galata Bridge is a unique experience.",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 1,
                            Stars = 5
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Sara K.",
                            Comment = "Very delicious but it can get crowded in the evenings.",
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 1,
                            Stars = 4
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Mert A.",
                            Comment = "Find this ramen in Tokyo, you won't regret it!",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 6,
                            Stars = 5
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Elif D.",
                            Comment = "Real Neapolitan pizza tastes completely different. Nothing compares!",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 10,
                            Stars = 5
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Can B.",
                            Comment = "Had ceviche in Lima — the best seafood experience of my life!",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 38,
                            Stars = 5
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Zeynep M.",
                            Comment = "Eating tagine in the streets of Marrakech is a one-of-a-kind experience.",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 40,
                            Stars = 5
                        });
                });

            modelBuilder.Entity("TasteTheWorld.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TasteTheWorld.Models.BucketList", b =>
                {
                    b.HasOne("TasteTheWorld.Models.Food", "Food")
                        .WithMany("BucketLists")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasteTheWorld.Models.User", "User")
                        .WithMany("BucketLists")
                        .HasForeignKey("UserId");

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TasteTheWorld.Models.Food", b =>
                {
                    b.HasOne("TasteTheWorld.Models.City", "City")
                        .WithMany("Foods")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TasteTheWorld.Models.Review", b =>
                {
                    b.HasOne("TasteTheWorld.Models.Food", "Food")
                        .WithMany("Reviews")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("TasteTheWorld.Models.City", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("TasteTheWorld.Models.Food", b =>
                {
                    b.Navigation("BucketLists");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TasteTheWorld.Models.User", b =>
                {
                    b.Navigation("BucketLists");
                });
#pragma warning restore 612, 618
        }
    }
}
